---
title: "Bayesian Regression"
output: pdf_document
---

```{r setup}
library(geoR)
library(mvnfast)
library(MCMCpack)
library(brms)
```

## loading data

```{r load data}
X_train <- read.csv("train-test/X_train_diff.csv")
X_test <- read.csv("train-test/X_test_diff.csv")
y_train <- read.csv("train-test/y_train.csv")
y_test <- read.csv("train-test/y_test.csv")

train_df <- cbind(X_train, POINT_DIFF = y_train$POINT_DIFF)
test_df <- cbind(X_test, POINT_DIFF = y_test$POINT_DIFF)

cat("Training rows:", nrow(train_df), "\n")
cat("Test rows:", nrow(test_df),  "\n")
```

## fitting model
```{r fit model}
# note the "." means all other columns

=prior <- default_prior(POINT_DIFF ~ .,
                       data = train_df,
                       family = gaussian())

manual_prior <- c(
  prior(student_t(3, 0, 5), class = "Intercept"),
  prior(student_t(3, 0, 5), class = "sigma"),
  prior(normal(0, 1), class = "b")
)

fit <- brm(POINT_DIFF ~ .,
           family = gaussian(),
           data = train_df,
           chains = 4,
           iter = 1000,
           warmup = 180,
           thin = 2,
           prior = manual_prior)

```

```{r summary}
summary(fit)
```

### chain trace plots/marginal posteriors for the 12 rolling features

```{r convergence plot, fig.height=18}

rolling_vars <- c(
  "b_PTS_roll10_diff",
  "b_FG_PCT_roll10_diff",
  "b_FT_PCT_roll10_diff",
  "b_FG3_PCT_roll10_diff",
  "b_AST_roll10_diff",
  "b_REB_roll10_diff"
)

plot(fit, variable = rolling_vars)
```

```{r posterior-hist, fig.height=8}
mcmc_plot(fit, variable = rolling_vars, type = "hist")
```

```{r posterior-acf, fig.height=8}
mcmc_plot(fit, variable = rolling_vars, type = "acf")
```

```{r posterior-sigma}
mcmc_plot(fit, variable = "sigma", type = "hist")
```

## evals

```{r r2}
bayes_R2(fit)
```

```{r coverage}
post_preds <- posterior_predict(fit, newdata = test_df)

lower <- apply(post_preds, 2, quantile, probs = 0.025)
upper <- apply(post_preds, 2, quantile, probs = 0.975)

coverage <- mean(test_df$POINT_DIFF >= lower & test_df$POINT_DIFF <= upper)
# too much variability, need more informatble priors, so rn inf variants on the weights.
cat(sprintf("95%% posterior predictive interval coverage on test set: %.1f%%\n", coverage*100))
```

```{r pred vs actual}
pred_mean <- colMeans(post_preds)

residuals <- test_df$POINT_DIFF - pred_mean

plot(seq_along(residuals), residuals,
     xlab = "Index",
     ylab = "Residual",
     main = "Residuals")
abline(h = 0, col = "red", lwd = 2)

mse <- mean((pred_mean - test_df$POINT_DIFF)^2)
cat("MSE (for comparison with the MLP):", mse)
```
